- hosts: all
  vars_files:
           - "{{  ansible_facts['distribution']  }}.yml"
  tasks:
          - name: Install Webserver
            package: 
                name: "{{ software_name }}"
                state: present

          - name : Copy file
            template:
                src: web.html.j2
                dest: /var/www/html/index.html
          - name: Service 
            service:
                name: "{{ service }}"
                state: started


